### ISSUE TITLE
Flag dropped data in bz_ePlayerDieEvent

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag#1]
Add the ability to keep track of what flag was dropped by the victim when they were killed.

A `bz_PlayerDieEventData_V2` would be required with this new information.

**Comment by allejo** [comment]
I don't think this could be done without making significant changes though I could be wrong; I'll assign to 2.6 for now.

**Comment by blast007** [comment]
Implemented by PR #64.

**Comment by allejo** [comment]
I'm going to reopen this issue as a reminder for 2.6 (hope no one minds); see #64 and #66 

See also: https://github.com/BZFlag-Dev/bzflag/blob/db0a06e45d82182d363040a1b4bf59f8466e99cb/src/bzfs/bzfs.cxx#L3133-L3143

Currently the client sends the flag drop message on death so bzfs doesn't see that the flag drop was caused because of the death event. I'd like to propose that either `bz_ePlayerDieEvent` contains data about what flag was dropped in result of the death or `bz_eFlagDroppedEvent` contains data about why it was dropped, e.g. player death, /flag take, bz_removePlayerFlag()

**Comment by JeffM2501** [comment]
I would close this and open a new one that specifically says to fix the order of messages. this item is about the API. fixing the order of the messages does not affect the API. a future developer should not be confused about it.
