### ISSUE TITLE
Stream map packets and only re-transmit if the client requests it

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#116]
Currently the game does a request/response model for map transfers, limiting the transfer to 1k for every full lag cycle. This is slow. Have the server buffer and send all map packets along with ordering info. Have the client request any that do not make it and respond with a “world done” message. This will make transfers much faster.

This may be implementable in the current protocol, have the server track/count ACK packets but send out all the messages one after another. This requires a buffering server.

(From @JeffM2501)

**Comment by JeffM2501** [comment]
Current code now does this, it’s at least as good as fastmap, and sometimes better.
