### ISSUE TITLE
Split messages that have different packs on the server and client into different messages

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#117]
Currently some messages are packed differently on the client then they are on the server. This makes unifying pack/unpack code difficult. The messages really should have different codes to make debugging and maintenance easier.

MsgGrabFlag should be split into MsgRequestFlag and MsgGrantFlag
MsgDropFlag should be split into MsgDropFlag and MsgFlagDroped (or just a Flag update with the correct state)
MsgMessage should be split into MsgSendChat and MsgReceiveChat
MsgTransferFlag should be MsgStealFlag and MsgRemoveFlag/MsgGrantFlag

(From @JeffM2501)

**Comment by timriker** [comment]
That was just a poke at the "Droped" misspelling. I presume you meant "MsgFlagDropped"

**Comment by JeffM2501** [comment]
You should know by now that I can't spell ;)

**Comment by JeffM2501** [comment]
Fixed
