### ISSUE TITLE
Unable to shoot on Linux and shots that end early never finish reloading

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#159]
~~I ran a local instance of bzfs and a client with -solo 5.  The solo bots no longer seem to shoot.~~

It actually seems to be shooting in general with a Linux client.  I managed to shoot once, I believe.  And on Windows, if the shot ends early, the reload timer for that slot never finishes.

**Comment by blast007** [comment]
709a5b5d201a1d498a12e97342122924cf203453 fixes the issue with reloading on Windows

**Comment by JeffM2501** [comment]
b59ba2a  fixes the shooting issue.
It was an uninited variable so it would be different every time it ran.
It did not happen in debug ether.
It did dupe in windows in release too.

I replaced the function entirely (it based reload checks on your current flag, not your actual slots), now it checks all slots and finds the slot that will end soonest.
