### ISSUE TITLE
Shooting yourself at close range does not end the shot and breaks respawning

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#161]
If you are facing a wall at close range (perhaps a tank length or less) and shoot yourself with a rico, your tank explodes, but the shot does not end (continues on the path through you) and you are unable to respawn.

**Comment by JeffM2501** [comment]
I believe I know what this is and am working on a fix.

**Comment by JeffM2501** [comment]
should be fixed with b857380
