### ISSUE TITLE
BZFlag in Flatpak (via Flathub)

### ISSUE THREAD

**Issue by rrigby** [BZFlag-Dev/bzflag#177]
Hi,
Just letting you know I've submitted a flatpak manifest for BZFlag to flathub.
https://github.com/flatpak
https://github.com/flathub

If you are interested in becoming the maintainer feel free to jump in here and let us know!
https://github.com/flathub/flathub/pull/539

**Comment by allejo** [comment]
Thank you very much for this!

[BZFlag has been added to flathub](https://github.com/flathub/flathub/pull/539#issuecomment-413555695) and is available at [flathub/org.bzflag.BZFlag](https://github.com/flathub/org.bzflag.BZFlag). I've been granted write access to the repository, so we'll be able to push updates for future releases.
