### ISSUE TITLE
'srvmsg' displays incorrectly

### ISSUE THREAD

**Issue by Zehra** [BZFlag-Dev/bzflag#189]
This occurs in Windows 10 using BZFS version 2.4.18.
A map file with the 'options' block containing several '-srvmsg' is specified.
They do not display correctly as seen below.

![text error](https://user-images.githubusercontent.com/22282963/52454895-aa225980-2b1b-11e9-9a61-446c81b1e1d0.png)

The map file is provided below.

[text-test.txt](https://github.com/BZFlag-Dev/bzflag/files/2843351/text-test.txt)

**Comment by allejo** [comment]
The `\` character has special meaning in a lot of things. You need to escape it in your options.

```
-srvmsg " ______        __ ______        __ "
-srvmsg "/_  __/__ ___ / //_  __/____ __/ /_"
-srvmsg " / / / -_|_-</ __// / / -_) \\ / __/"
-srvmsg "/_/  \\__/___/\\__//_/  \\__/_\\_\\__/ "
```

![image](https://user-images.githubusercontent.com/1246453/52455304-43457600-2b04-11e9-9932-b2266ebc7d76.png)

**Comment by blast007** [comment]
It would be useful to document what escape sequences we support.
