### ISSUE TITLE
bzfscron server side player does not join

### ISSUE THREAD

**Issue by Zehra** [BZFlag-Dev/bzflag#192]
This bug occurs when using bzfscron in 2.4.18 on the Windows platform.

The following options are specified and the plug-in is loaded at start-up of BZFS.

```bzfs.exe -ddd -loadplugin bzfscron,bzfscron.cfg```

What occurs is the serverSidePlayer appears to join, but does not join.
The commands within the configuration file are properly run, but 'bzfscron' does not appear.
(Either within the scoreboard or via the '/lagstats' command.)

**Comment by blast007** [comment]
This works correctly in the master branch.  Given that SSPs were quite limited in 2.4, I don't think we'll fix it there.
