### ISSUE TITLE
Steamroller killed by OO

### ISSUE THREAD

**Issue by Zehra** [BZFlag-Dev/bzflag#198]
The following bug occurred on a Windows 10 machine with client version **2.4.6-RC2** on the receiving end.

![image](https://user-images.githubusercontent.com/22282963/58138251-61426c80-7c03-11e9-9e8e-6361c9a0ee16.png)

Reproduction of bug is unknown as it was seen on a public server.

**Comment by allejo** [comment]
If you could provide any information about the situation or steps to replicate this, that'd be helpful. Otherwise, we're flying blind.

**Comment by Zehra** [comment]
Both flag grabs happened within a minute of each other.
(Most likely even less then 30 seconds.)

As for precise information, the details would be within the server logs.
Map type: **Urban Jungle**
Server: **bzflag.allejo.io:5130** 
Time frame: approximately 24 hours ago at 5/21/2019.

**Comment by allejo** [comment]
I don't log flag grabs or player deaths, that'd be too much information to store for a production server. Besides, it's unlikely timestamps/text would really help us find anything.

> Both flag grabs happened within a minute of each other.

Ideally, we'd need more thorough replication steps or a replay file of the incident occurring. Flags can be grabbed seconds apart on any given server and this bug doesn't occur. Has this happened anywhere else besides UJ? It could be a plug-in is causing this behavior.

**Comment by Zehra** [comment]
I later realized this when checking the source of LogDetail.

> Ideally, we'd need more thorough replication steps or a replay file of the incident occurring. Flags can be grabbed seconds apart on any given server and this bug doesn't occur. Has this happened anywhere else besides UJ? It could be a plug-in is causing this behavior.

This is the first and only time I have personally witnessed this bug occur.
Thus I am unaware of the precise conditions required to reproduce this bug.

I do however recall the death occurred in a jump, if I'm not mistaken.

**Comment by blast007** [comment]
Looking at the game logic, the steamroll death should only occur if the other player has the SteamRoller flag or if your client's Z coordinate is less than 0.  Without more specific information (such as a replay file) there's not much we can investigate here.
