### ISSUE TITLE
NetHandler Compiling Error

### ISSUE THREAD

**Issue by sodomon2** [BZFlag-Dev/bzflag#205]
I have a compilation error with NetHandler Here's the error

```
mv -f $depbase.Tpo $depbase.Plo
NetHandler.cxx: In static member function 'static int NetHandler::udpReceive(char*, sockaddr_in*, bool&)':
NetHandler.cxx:149:22: error: invalid conversion from 'int*' to 'socklen_t*' {aka 'unsigned int*'} [-fpermissive]
                      &recvlen);
                      ^~~~~~~~
In file included from ../../include/PlayerInfo.h:23,
                 from ../../include/NetHandler.h:25,
                 from NetHandler.cxx:14:
/usr/include/fortify/sys/socket.h:46:73: note:   initializing argument 6 of 'ssize_t recvfrom(int, void*, size_t, int, sockaddr*, socklen_t*)'
                                        struct sockaddr *__a, socklen_t *__l)
                                                              ~~~~~~~~~~~^~~
make[2]: *** [Makefile:500: NetHandler.lo] Error 1
make[2]: Leaving directory '/home/diego/Descargas/FPS/games/bzflag-2.4/src/game'
make[1]: *** [Makefile:428: all-recursive] Error 1
make[1]: Leaving directory '/home/diego/Descargas/FPS/games/bzflag-2.4/src'
make: *** [Makefile:488: all-recursive] Error 1
```

**Comment by allejo** [comment]
Can you please provide the following information?

- git branch you're building
- linux distribution
- distribution version
- version of `gcc`

**Comment by jwmelto** [comment]
I'm having a hard time determining how this can happy. On line 142
```c++
    AddrLen recvlen = sizeof(*uaddr);
```
`AddrLen` is defined in network.h starting at line 60:

```c++
#if defined(BSD) || defined(__sun__) || defined(__GLIBC__)
#  define AddrLen       socklen_t
#elif defined (__APPLE__)
#  include <AvailabilityMacros.h>
#  if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_4
#    define AddrLen     socklen_t
#  endif
#endif
```

However, there is a fall-through case (windows? other unix?) starting at line 133
```c++
#if !defined(AddrLen)
#  define AddrLen       int
#endif
```
that would account for the error.

I wonder if there is a better test for Posix conforming-ish environments where we can just use `socklen_t`?

**Comment by jwmelto** [comment]
however, the Winsock definition for `recvfrom` is 
```c++
int recvfrom(
  SOCKET   s,
  char     *buf,
  int      len,
  int      flags,
  sockaddr *from,
  int      *fromlen
);
``` 
so `int*` is correct on Windows

**Comment by diazvictor** [comment]
I also had the same error, but after editing NetHadler.cxx no longer gave me the error, but then gave me another error in bzfs.cxx. here the error

```bash
ed-char -fexpensive-optimizations -g -O2 -MT bzfs.o -MD -MP -MF $depbase.Tpo -c -o bzfs.o bzfs.cxx &&\
mv -f $depbase.Tpo $depbase.Po
bzfs.cxx: In function 'void acceptClient()':
bzfs.cxx:1315:63: error: invalid conversion from 'int*' to 'socklen_t*' {aka 'unsigned int*'} [-fpermissive]
     int fd = accept(wksSocket, (struct sockaddr*)&clientAddr, &addr_len);
                                                               ^~~~~~~~~
In file included from /usr/include/fortify/sys/socket.h:22,
                 from ../../include/network.h:38,
                 from bzfs.h:29,
                 from bzfs.cxx:14:
/usr/include/sys/socket.h:329:47: note:   initializing argument 3 of 'int accept(int, sockaddr*, socklen_t*)'
 int accept (int, struct sockaddr *__restrict, socklen_t *__restrict);
                                               ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:779: bzfs.o] Error 1
make[2]: Leaving directory '/home/user/games/bzflag-2.4/src/bzfs'
make[1]: *** [Makefile:428: all-recursive] Error 1
make[1]: Leaving directory '/home/user/games/bzflag-2.4/src'
make: *** [Makefile:488: all-recursive] Error 1
```
Here is the pache for NetHadler.cxx


[patch.patch.txt](https://github.com/BZFlag-Dev/bzflag/files/3404642/patch.patch.txt)

**Comment by sodomon2** [comment]
I'm building away from the master branch.
```
Distribution  [Alpinelinux.](http://alpinelinux.org/)
Alpine Linux v3.9
gcc 8.3.0
```

**Comment by sodomon2** [comment]
> Can you please provide the following information?
> 
>     * git branch you're building
> 
>     * linux distribution
> 
>     * distribution version
> 
>     * version of `gcc`

I'm building away from the master branch.
```
Distribution Alpinelinux.
Alpine Linux v3.9
gcc 8.3.0
```

**Comment by jwmelto** [comment]
Alpine doesn't use GLIBC, which is what the code expects. I personally think the test is too restrictive.

For a quick fix, you can modify network.h on line 60 and add a symbol defined by your system. You can see all the symbols using

    touch foo.cc
    g++ --std=c++11 -E -dM -c foo.cc

**Comment by blast007** [comment]
Would adding a check for `__GNUC__` be a solution?  Or is Windows the odd duck and we just define it as `int` for Windows and as `socklen_t` for everything else?

**Comment by jwmelto** [comment]
I can't find any Linux documentation that has anything other than `socklen_t`. That's the POSIX definition. I think a WIN32-specific override should be reasonable, but I'm hoping someone with more cross-platform experience can weigh in.

**Comment by blast007** [comment]
PR #217 has been merged, so this should be resolved now.
