### ISSUE TITLE
Teleporter naming in world export, obj format

### ISSUE THREAD

**Issue by ODelusion** [BZFlag-Dev/bzflag#233]
When " /saveworld -o" is used to export in obj format, the teleporters are written into the file in any order, mixed up with "bzbox" and other objects.
If teleporters were written into the file FIRST, before all other objects, the "bztele_0.. bztele_1, etc." numbers delivered to the .obj file would match the "/t0 , /t1, etc." numbers in the original .bzw format file.
AFAIK, it's the only place where the name of the object matters. Any other object name is not even transferred  from the .bzw to the .obj.  That would be a nice feature too.

**Comment by allejo** [comment]
An example to point out this problem, teleporter names are saved in a bzw export but they're lost in an obj export. In the obj export, it's named `bztele_23`, since it's just using an autoincrementing UID for each map object.

```
teleporter /t0
  position 48.5 73.5 70
  size 0.125 18.1 5
  rotation 56.25
  border 0
end
```

```
# OBJ - start tele
o bztele_23
v 89.90853882 -1.27659798 70.00000000
v 90.15373230 -1.22782707 70.00000000
v 83.09146118 34.27659607 70.00000000
v 82.84626770 34.22782898 70.00000000
v 89.90853882 -1.27659798 75.00000000
v 90.15373230 -1.22782707 75.00000000
v 83.09146118 34.27659607 75.00000000
v 82.84626770 34.22782898 75.00000000
vt 0.00000000 0.00000000
vt 1.00000000 0.00000000
vt 1.00000000 1.00000000
vt 0.00000000 1.00000000
vn 0.19509032 -0.98078531 0.00000000
vn 0.98078537 0.19509034 0.00000000
vn -0.19509032 0.98078531 0.00000000
vn -0.98078537 -0.19509034 0.00000000
vn 0.00000000 0.00000000 -1.00000000
vn 0.00000000 0.00000000 1.00000000
usemtl telefront
f -7/-4/-5 -6/-3/-5 -2/-2/-5 -3/-1/-5
usemtl teleback
f -5/-4/-3 -8/-3/-3 -4/-2/-3 -1/-1/-3
usemtl telerim
f -5/-4/-2 -6/-3/-2 -7/-2/-2 -8/-1/-2
f -4/-4/-1 -3/-3/-1 -2/-2/-1 -1/-1/-1
f -8/-4/-6 -7/-3/-6 -3/-2/-6 -4/-1/-6
f -6/-4/-4 -5/-3/-4 -1/-2/-4 -2/-1/-4
```
