### ISSUE TITLE
Mouse stuck outside game window when leaving fullscreen

### ISSUE THREAD

**Issue by khonkhortisan** [BZFlag-Dev/bzflag#25]
Windows 10
BZFlag v.2.4.4 RC1
Options→Input Settings→Confine mouse: MotionBox
Options→Display Settings→Change Video Format: 1600x900 @60Hz 32 bits
Options→GUI Settings→Mouse Box Size: [-----O----------------]
Join Game→Connect
Spawn
F1

Mouse is centered in the middle of the screen, while the game window is in the top-left corner.
Ctrl does not release the mouse.
If the mousebox was large enough to have a corner of the screen-centered mouse area overlap the window area, it could recenter on the window
Win+Tab to focus a specific window releases the mouse from being centered.

#15: "On some platforms, there are reports that if the mouse escapes the window or motionbox (probably between frames), it remains there until moved back into the window."

**Comment by blast007** [comment]
Duplicated here on Windows 7.  It also does not free the cursor if you die or go into a menu, nor does it bring the cursor back to the center of the window when you respawn.
