### ISSUE TITLE
GlobalShotList sometime contains an element with null pointer. 2.5

### ISSUE THREAD

**Issue by atupone** [BZFlag-Dev/bzflag#274]
Tested on ratnest with solo bots.
This is how to replicate the problem

Team Kill your friend until expelled.
Rejoin just after. your client will crash

**Comment by atupone** [comment]
The problem seems to be in src/bzflag/ShotList.cxx in ClearPlayerShots
 void ClearPlayerShots(PlayerId player)
 {
    std::remove_if(GlobalShotList.begin(), GlobalShotList.end(), [&](const ShotPath::Ptr& shot)
    {
        return shot != nullptr ? shot->getPlayer() == player : false;
    });
}
When it happens if I print the list just before the remove_if and I print the get() for each element of the GlobalShotList no element is null.
If I print after I found one element null.
If I understand well the remove_if this should not change any element, it should remove it.
Is this some interaction with the shared_ptr ?

**Comment by jwmelto** [comment]
The test `shot != nullptr` is malformed. It should probably be `shot && (*shot != nullptr)` or some equivalent construct.

**Comment by atupone** [comment]
I removed that test and leaved only
return shot->getPlayer() == player;
as shot should not be nullptr.
But still one element in the list changes to null.
Maybe during the move of the element called the destructor of the shared_ptr for the next elements ?

**Comment by jwmelto** [comment]
I double checked [the documentation](https://en.cppreference.com/w/cpp/algorithm/remove) and it confirmed my suspicion that `std::remove_if` doesn’t erase elements (unlike `std::list::remove_if`). If you see the example, the return value should be used to erase the removed elements of the container. 

Good find.

**Comment by jwmelto** [comment]
But don’t remove the test for `nullptr`, just do a proper test. `std::shared_ptr::operator bool()` will tell you if the object has a valid pointer; do check before dereferencing.

**Comment by atupone** [comment]
Well that was just a test. I expected, has I already said, that remove will not modify any element

**Comment by atupone** [comment]
ok I did not check your previous answer

**Comment by atupone** [comment]
I left the test code as it was and used std::list:remove_if

Seems to work. 

There are other Std::remove_if in the code. I hope they are ok as it call std::erase just after

**Comment by jwmelto** [comment]
To be clear, `std::remove_if` **does** modify _elements_, as it performs move copies over the “removed” elements. It just doesn’t modify the container by erasing elements.
