### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by bluecoat58** [BZFlag-Dev/bzflag#281]
When one picks up a flag, there is a text line describing what it does. You should be able to turn this off.  It is really annoying that this pops up, over and over and over again.

**Comment by kongr45gpen** [comment]
Have you tried pressing the `F` key on your keyboard while holding a flag? :wink:

**Comment by blast007** [comment]
Yes, the key to toggle flag help is mentioned in both the key mapping screen and the help menu.
