### ISSUE TITLE
Dual Monitors

### ISSUE THREAD

**Issue by bluecoat58** [BZFlag-Dev/bzflag#282]
Bzflag is really horrible on dual monitor handling. You should be abe to 
a) spread the playfield out over ALL monitors seamlessly.
b) have radar  and/or chat on a separate monitor.
c) Correctly exit the game without screwing up the desktop setup (which currently happens in linux)( I only have one monitor displaying after quiting the game.

**Comment by blast007** [comment]
Which version of BZFlag are you using and it is using SDL or SDL 2?  (The version should indicate -SDL or -SDL2)

**Comment by bluecoat58** [comment]
Sorry I took so long.  Using sdl2-config --version it reports back with 2.0.16.
When I exit bzflag only one monitor is usable. I have to log out and back in to regain both monitors.

**Comment by blast007** [comment]
Please provide the version of BZFlag that you are using and let us know if it's actually using SDL2.  Again, the BZFlag version should end in -SDL or -SDL2, which indicates which version of SDL (1 or 2) it is linked against.

**Comment by bluecoat58** [comment]
I've tried the DEB version 2.4.20.20200516-MAINT-linux-gnu-SDL
The version I compiled is: 2.4.22.20211106-MAINT-linux-gnu-SDL2

## same results in both.

**Comment by bluecoat58** [comment]
Ok, I just dl'd the latest version: BZFlag client 2.4.23.20211211-DEVEL-linux-gnu-SDL2 
And compiled it.  It works PERFECTLY on dual monitors.  Thanks for the work guys!
