### ISSUE TITLE
Player appears cloaked, but isn't.

### ISSUE THREAD

**Issue by jbum** [BZFlag-Dev/bzflag#29]
I'm using 2.4.4 RC2, for Mac OSX.  On the Clay Hills server, a particular player (not known for cheating) was invisible on main screen for duration of game.  Other players were fine.  I quit the app, restarted it and signed back, and the same player was still invisible.  I also seemed unable to land a bullet on this player.  They showed up on the radar fine, and I could see their shots.

I was able to make the problem go away by using 2.4.2 on the same server. When I next launched 2.4.4 RC2 the problem had gone away, but on a subsequent launch it reappeared after a couple minutes of play.  Each time, it was the same player who was invisible/unshootable.

**Comment by jbum** [comment]
I was able to make the problem go away by using 2.4.2 on the same server.  But subsequently, I could not reproduce it with 2.4.4 RC2.

**Comment by jbum** [comment]
An Update.  An hour or two later, I signed onto the same server and played for a few minutes.  At this point, the same player signed on from before, and again, I couldn't see, nor shoot the player (Miss American Pi).  It appears there is something about that particular player that is triggering the bug.

**Comment by kongr45gpen** [comment]
There is at least one spot in that map that can be accessed through a tiny gap (thus requiring the Tiny flag) close to the river. That area has a window that is transparent only through the player's side and opaque to the outside, making the player essentially invisible out of the window. However, that window is shootThrough, meaning shots can get through it.

Are you sure that player was not in that hidden area of the map?

**Comment by jbum** [comment]
It was occurring all over the map...

Jim

**Comment by macsforme** [comment]
Can you verify one more time that it occurs all over the map? I was playing with that person, and I thought I saw the same thing you did, but then when I joined in observer to see what was going on, that player was indeed in a hidden area of the map just below the surface. You might try joining in observer yourself to see if that affects the visibility of the player.

**Comment by jbum** [comment]
Closing this, as it's possible this is just the hidden area on that map and I was deluded.
