### ISSUE TITLE
Rendering issue when using SDL1

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#295]
I noticed a rendering regression caused by 53e166968306fa13460e545759466c642459cc17 when building against SDL1.  I have tested this on Debian 11 with a Radeon RX 570.  There, the issue only occurs when running fullscreen.  It works fine under SDL2, so it's not immediately clear why there would be a difference.

![bzfi0002](https://user-images.githubusercontent.com/328999/144960994-101fd095-f7d2-45e5-b763-9f03e557bb07.png)

**Comment by atupone** [comment]
SDL1 is no more with us
