### ISSUE TITLE
Events are not processed when using SDL 2.0.20

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#301]
When built against SDL 2.0.20, input events are not handled, so it's not possible to use the keyboard or mouse to interact with the game.  In addition, I'm not sure if events are being processed at all since I also get an unresponsive application alert, at least on Fedora 35.

So far I've tested on Fedora 35 with their included binary package and built from source, and I've also compiled from source against a self-compiled SDL 2.0.20 on Debian 11.  All exhibit the problem.  I have not tested on other platforms.

**Comment by blast007** [comment]
BZFlag breaks after this change in SDL: [Move special sentinel handling inside SDL_PeepEvents()](https://github.com/libsdl-org/SDL/commit/954858846d2883864b4e5fef55f31bb92f1514cc)

**Comment by macsforme** [comment]
For the record, this issue also manifests on macOS with SDL 2.0.20.  I tested it on Mojave and Monterey, both Intel and ARM, and the issue was present in all scenarios.

**Comment by jeffpc** [comment]
Similarly, the FreeBSD packages are affected.  The game starts, but keyboard/mouse events have no effect.  The package versions on FreeBSD are:

```
$ pkg info|egrep '(sdl|bzflag)'
bzflag-2.4.22_1                Multiplayer 3D tank battle game
sdl2-2.0.20_1                  Cross-platform multimedia development API
sdl2_image-2.0.5               Simple library to load images of various formats as SDL surfaces
```

**Comment by blast007** [comment]
A workaround for this issue was added in BZFlag 2.4.24.
