### ISSUE TITLE
Phantom Zone

### ISSUE THREAD

**Issue by kaadmy** [BZFlag-Dev/bzflag#31]
I have found out this while playing on Quickshot.

If you grab a PZ flag, then become zoned by driving through a teleport, you can lose the flag by using up your shot limits to become un-zoned at any time you want, without a teleporter.
But if you get un-zoned that way, without going back through a teleporter, then try to pick up a PZ flag again, you get re-zoned without needing to go through a teleporter.

I don't know how this could be fixed, as it's partly a map problem with the shot limit, but the PZ state should be reset when the flag is dropped.

**Comment by allejo** [comment]
Confirmed

**Comment by jbum** [comment]
I always thought this was a feature of that particular map... :)
