### ISSUE TITLE
Server countdown timer runs faster on Windows bzfs

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#32]
The countdown timer runs significantly faster on Windows bzfs instances, jumping ahead about 10 seconds every 30 seconds (the interval that it sends out updates to clients).  The countdown timer in the Windows client itself runs at the correct rate.

**Comment by blast007** [comment]
This seems to be caused by the QPC recalibration code in TimeKeeper.cxx, which was added back in the 2.0.x days to fix a client jitter issue that a user was experiencing (likely because of CPU frequency changes).  I'm not seeing the issue in the client because the recalibration is being called often enough that we're not getting large jumps.  The server sometimes has several seconds of sleep time between game loops.

I wasn't able to duplicate the old issue on a 2.0.2 client on my old Windows XP laptop with a single core Pentium M nor on a Windows 10 laptop with a dual core i7.  Because of that, I am reassigning this to the 2.6 milestone since it will need more testing to see if we can remove that recalibration code.

Currently we store the current time in TimeKeeper in the ```seconds``` variable and do math every time to add the time that has passed to the current time.  This probably suffers from precision issues over time as it's doing floating point math every time.  SDL2 has a timer class that is much simpler and stores a start time and just does the math once based on that start time.

**Comment by JeffM2501** [comment]
This should be fixed now with recent changes.
