### ISSUE TITLE
OSX zoom feature freezes computer.

### ISSUE THREAD

**Issue by ODelusion** [BZFlag-Dev/bzflag#325]
When my BZflag client is in fullscreen mode, then i attempt to use the OSX zoom feature (found in accessability settings panel), the BZ client freezes, and i lose mouse control.  Force-quit key commands do not seem to activate. The only way to regain computer control is a hard restart.
OSX 13.2.1, M1 mac mini.

**Comment by blast007** [comment]
Is this still an issue?  I tried on my M1 mac mini running macOS 15.1.1, and I couldn't get the zoom function to function while fullscreen.  I switched the game to windowed and I was able to adjust the zoom without issue, and switch back to fullscreen while still zoomed in.

**Comment by ODelusion** [comment]
No longer an issue. Apple fixed it in OSX 14. Now we are on 15.

**Comment by Juesto** [comment]
but the issue remains for older macos versions, right?

**Comment by ODelusion** [comment]
I'm pretty sure it's only OSX 13. And might be only OSX 13.2.
The thing is, I don't think it's a BZFlag issue, it's an OSX issue. And updating OSX is so useful, easy, and free, that not many users will stay with an older version without a compelling reason to do so. And no compelling reason exists.
