### ISSUE TITLE
Gameover doesn't kill players

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag#33]
Reported by Mopar Madness:
> I found a bug in the countdown plugin on BZFlag.Allejo.io:5158, not sure if its 2.4.4 related or plugin related. Players who are alive when the countdown ends or gameover is called can be /killed by admins after the game ends even though they are already dead. Attempting to kill them again results in "player is not alive" message. Attempting to kill players already dead at the time of the game ending also results in "player not alive". It affects all 2.4 clients and seems to be either server or plugin related. The server is running build 2.4.3.20150915-DEVEL-linux-gnu.

I haven't looked into this, but I think this is probably related to the fact that clients kill themselves instead of the server killing players (correct me if I'm wrong).

**Comment by JMakey** [comment]
Clients receiving MsgScoreOver call explodeTank() but they don't immediately drop flags and they don't send MsgKilled.  It has been this way since 2.0.x and probably longer, but fixing it won't affect gameplay so now would be a fine time to do it.
