### ISSUE TITLE
Game fails to run on Windows 10 (and maybe 7/8/8.1) with modern AMD graphics

### ISSUE THREAD

**Issue by blast007** [BZFlag-Dev/bzflag#35]
I have been working on this issue for a couple weeks now and still haven't been able to figure out why it is failing to run.  This is release critical, so we need to fix it before the 2.4.4 release, and I need some help with it.  I'm not familiar enough with what is going on in the Windows platform code.

When the game starts, it ends up creating a child window and then trying to destroy it again.  I believe the destroying part is just because it's going fullscreen, and display changes recreate the child window.  In any case, it gets stuck in `DestroyWindow(hwndChild)` inside of the `WinWindow::destroyChild()` method.  I set up some tracepoints in `WinWindow::createChild()`, `WinWindow::swapBuffers()`, `WinWindow::destroyChild()`, and `WinDisplay::Rep::WindowProc(...)` and ran the game client.  The output of that (edited to show what the msg value refers to) as [trace01.txt](https://github.com/BZFlag-Dev/bzflag/files/72570/trace01.txt).

The system I am using has an AMD A10 Micro-6700T SoC, which has AMD Radeon R6 Graphics, running Windows 10 64-bit.  I've tried using the latest stable driver from AMD (Radeon Software version 15.11, driver version 15.30.1025-151117a-296567C) and the latest beta (Radeon Software version 15.11.1, driver version 15.30.1025.1001-151129a-297019E).

NTH originally reported the issue.  He's got a Radeon HD 78xx card running Windows 10 build 10586.14 with AMD driver version 15.30.1025-151117a-296567C.  He mentioned the issue started after Windows 10 updated.  So I'm not sure if it's a Windows 10 issue or an AMD driver issue.

I did *not* have an issue on a laptop with Intel/AMD hybrid graphics using a Radeon HD 8690M, but that may just be due to the hybrid graphics.

This issue may be the same or related: https://forums.bzflag.org/viewtopic.php?f=12&t=19152

Initially, our release of 2.4.2 worked, and then 2.4.4RC2 (or my other builds I ran) would work until a reboot.  Now our old 2.4.2 build is having the same issue.  Running the game windowed does work, but will still hang if you switch it to full screen.

**Comment by jwmelto** [comment]
I'm afraid I can't help with Windows, but just guessing it sounds like an SDL issue. Did the SDL version get upgraded?

**Comment by blast007** [comment]
Our Windows builds don't use SDL.  There is Windows specific platform classes/code that get used.

**Comment by blast007** [comment]
This issue will be pushed back to the 2.4.6 release so we can get a release out.  A possible solution would be to switch to using SDL2 on Windows.
