### ISSUE TITLE
Virustotal.com false positives

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag#363]
Or at least I hope they're false-positives...

https://www.virustotal.com/gui/file/3c84287e41c4ed697f13a2116bdd05f11098d2c4e262be0f080e0c019edbd96b

![image](https://github.com/user-attachments/assets/019a03a0-cc5b-4c5a-aa28-67f6ccb1d984)

/cc @blast007

**Comment by blast007** [comment]
The ZoneAlarm one already seemed to fix the false positive.  The rest of the products I've never heard of before and I wouldn't put much faith into.
