### ISSUE TITLE
Strings in configuration file containing ; (semicolon) get truncated

### ISSUE THREAD

**Issue by erezwanderman** [BZFlag-Dev/bzflag#40]
My password contains a semicolon. When I enter it and connect it works well, but when I exit and connect again I notice that the password field is shorter, the semicolon and anything after it is removed.
If I connect I get rejected for wrong password. This also applies to the Callsign field and possibly any string field.

Steps to reproduce:
Start the game. Select Join Game in main menu.
Enter Callsign: 123;123
Enter Password: 123;123
Exit the game.
Start the game again, select Join Game.
Notice Callsign and Password are now "123" instead of "123;123"

Tested with BZFlag client 2.4.2.20140102-MAINT-linux-gnu-SDL (protocol 0221) http://BZFlag.org/

**Comment by kongr45gpen** [comment]
Fixed, thanks!
