### ISSUE TITLE
Pausing the countdown no longer shows "Paused"

### ISSUE THREAD

**Issue by macsforme** [BZFlag-Dev/bzflag#50]
In BZFlag 2.4.4, pausing the countdown no longer shows the "Paused" text at the top of the screen. Instead, the timer appears to continue running. When the countdown is resumed, the timer resets to the correct time from when it was paused. This occurs whether it is paused from a plugin, or paused with the command "/countdown pause."

**Comment by macsforme** [comment]
Using "git bisect" and some testing by hand, I determined that this issue was introduced in commit 1bd3782b

Perhaps @allejo could have a look?

**Comment by jwmelto** [comment]
Lines 683 is probably the culprit. By setting countdownPauseStart before the conditional on line 6708, the condition will never be true.
