### ISSUE TITLE
Server list does not completely show when main window is re-adjusted

### ISSUE THREAD

**Issue by Zehra** [BZFlag-Dev/bzflag#85]
The game client does not show the complete title of the server when the main window is re-adjusted in size.
The client version used is 2.4.6.20160319-RC2-Win32VC10-SDL2 on Windows 10.
![screenshot](https://user-images.githubusercontent.com/22282963/30243775-0618a016-957f-11e7-84d1-19438eacd0cf.png)

**Comment by allejo** [comment]
I don't believe server names ever wrap around. Was there an earlier version where they did?

**Comment by Zehra** [comment]
I haven't seen the server names wraparound from the versions I've seen.
I'm unsure if this would be the best option, but was expecting the text to resize to fit in the screen.

**Comment by allejo** [comment]
Scaling the text down could cause really small fonts and it would introduce inconsistencies. I don't think there are enough servers with long names and small screens to justify a fix for this; at least in the 2.4.x branch. This could be revisited in 2.6 when the UI is redesigned.

I'll leave this open for a little while longer to get feedback from anyone else who wants to weigh in.
