### ISSUE TITLE
bzflag won't open a retina mac with hidpi scaled resolutions

### ISSUE THREAD

**Issue by mikeage** [BZFlag-Dev/bzflag#87]
This bug was actually fixed in commit 33bfdccd, but it was reverted in 8b1067f with the note "Removed the workaround from since the issue was fixed upstream in SDL 2." 

SDL hasn't yet released this fix (the bug exists in SDL 2.0.5, which is the current stable release), and so I think that the workaround should remain until it's fixed in the stable release.

**Comment by allejo** [comment]
Workaround was removed because it was fixed in SDL 2.0.6, so we've been waiting for [SDL 2.0.6](https://discourse.libsdl.org/t/sdl-2-0-6-prerelease/23024) to be released so we can release 2.4.12.

**Comment by mikeage** [comment]
Right, but 2.0.6 isn't out yet, which compiling from source is broken. I was proposing keeping this in until the new SDL is released. (the reason I first tried compiling from source to see if this bug in 2.4.10 was fixed, and I still had to revert the revert to be able get a valid config.txt)

**Comment by mikeage** [comment]
Yes, recompiling with the tip and deleting my bzflag config resulting in generating a valid file. Thanks!
