### ISSUE TITLE
fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by cova-fe** [BZFlag-Dev/bzflag#94]
I'm facing some issues in compiling bzflag.
Version: 2.4.12
Gcc: 7.3.0
libsdl 1.12.15 and 2.0.7
distro: gentoo
Error:
```
/bin/sh ../../libtool --silent  --tag=CXX  --silent --mode=compile x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../include   -I../../include   -O2 -fpie -fpic -pipe -march=native -fstack-protector-strong -flto=4 -fuse-linker-plugin -c -o RenderNode.lo RenderNode.cxx
In file included from OpenGLGState.cxx:1635:0:
../../include/bzfSDL.h:24:14: fatal error: SDL.h: No such file or directory
 #    include "SDL.h"
              ^~~~~~~
compilation terminated.
```
The compilation fails in the same way also for versions 2.4.12/10/8; it works for version 2.4.6

Maybe this could be of interest (from config.log for 2.4.12)

```
configure:20895: x86_64-pc-linux-gnu-gcc -c -O2 -fpie -fpic -pipe -march=native -fstack-protector-strong -flto=4 -fuse-linker-plugin  conftest.c >&5
In file included from /usr/include/SDL2/SDL_config.h:10:0,
                 from /usr/include/SDL2/SDL_stdinc.h:31,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from conftest.c:131:
/usr/include/x86_64-pc-linux-gnu/SDL2/SDL_config.h:33:10: fatal error: SDL_platform.h: No such file or directory
 #include "SDL_platform.h"
          ^~~~~~~~~~~~~~~~
```
It can be a problem in my setup, however I'm unable to find it.
If more info can be useful, just ask.

**Comment by allejo** [comment]
Do you have the `*-dev` packages installed of SDL or just the libraries? The dev packages contain header files needed to compile things. On Debian distros, the respective packages are `libsdl2-dev` and `libsdl1.2-dev`; not sure what Gentoo has.

Additionally, when you run `./configure` there's a `--with-SDL` flag you can use to specify the SDL version you want to build with, which may be of some help; e.g. `--with-SDL=2`

**Comment by cova-fe** [comment]
Yes, being a "compiled" distro, gentoo has by default all headers and "dev" packages. Moreover, 2.4.6 gets compiled fine. 
I'll try to play a bit with SDL flags, but it seems that autotools are failing to correctly set up the correct headers.

**Comment by maggu2810** [comment]
I run into a similar problem on another package but found your issue report.
Please have a look at:
* https://bugs.gentoo.org/634296
* https://bugs.gentoo.org/634470
* https://bugs.gentoo.org/639410

The bug report "https://bugs.gentoo.org/634470" solves this by adding the SDL2 include path.
Perhaps it helps for your problem, too.

**Comment by cova-fe** [comment]
Indeed, on Gentoo adding a `append-cppflags "-I/usr/include/SDL2"` in `src_configure` in ebuild file made the trick, the compilation is now successful.
Many thanks for the hint, going to open a report on gentoo bugtracker, even if reading the bugs you posted (namely: https://bugs.gentoo.org/634370#c3 ) even upstream can do something. 
Thanks again

**Comment by jorgicio** [comment]
My 20 cents:

Create a file in your /etc/portage/env directory (if doesn't exist, create it) named, i.e. sdl2.

Its content must be this:

`CPPFLAGS=${CPPFLAGS} -I/usr/include/SDL2`

Then, add this to your /etc/portage/package.env file:

`games-action/bzflag sdl2`

You can specify the version too.

This works flawlessly. Just tried here.

**Comment by cova-fe** [comment]
Right you are, I forgot about env file. Thanks for reminding me this feature, now it compiles.
Thanks again

**Comment by allejo** [comment]
As someone who isn't familiar with Gentoo, is there something we (the BZFlag project) need to change/fix to resolve this or is this an issue with Gentoo?

**Comment by jer-gentoo** [comment]
https://bugs.gentoo.org/634660

Gentoo isn't very special at all. It uses autotools just like any other distro to build and install bzflag.

In this case, a newer SDL2 changed the way its header files are installed. To detect better where those are, use `sdl2-config --cflags` or preferably `pkgconfig --cflags sdl2` to discover the include path, perhaps using a patch such as [1].


[1] https://gitweb.gentoo.org/repo/gentoo.git/tree/games-action/bzflag/files/bzflag-2.4.12-sdl2-cppflags.patch
