### ISSUE TITLE
'Radar' setting 'Panel' opacity at 100% when radar is set to 100% opacity

### ISSUE THREAD

**Issue by Zehra** [BZFlag-Dev/bzflag#98]
*Screenshots taken in BZFlag-2.4.12 on Linux Ubuntu.*
When trying to change the radar or panel to either 100% opacity, it will carry the other setting.
If the panel setting is moved to 100% opacity, it will change the radar to 100% opacity as well.
This happens if the radar to changed to 100% opacity, it changes the panel to 100% opacity as well.

**Radar panel at almost 100% opacity and acting normal.**
![bzfi0000](https://user-images.githubusercontent.com/22282963/35200298-6fbb90be-fed9-11e7-99c9-476e4ff589c0.png)

**Radar at 100% opacity, but adjusting panel to 100% opacity without any action taken there.**
![bzfi0001](https://user-images.githubusercontent.com/22282963/35200302-7bd02c0c-fed9-11e7-8576-d77e9bbf205e.png)

**Comment by macsforme** [comment]
This is the expected behavior. Putting opacity at 100% puts the radar and console into a special mode that occupies the entire bottom area of the screen.
